#!/usr/bin/env bash

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

source /opt/conda/etc/profile.d/conda.sh

conda activate base

conda info

git config --global user.name "stackvana docker"
git config --global user.email "stackvana-docker@email.to.nowhere.com"

echo " "
echo "==================================================================================================="
echo "==================================================================================================="

$@
