name: tests
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build docker image
      run: |
        docker build -t stackvana:latest .

    - name: test image works
      run: |
        docker run --rm -t stackvana:latest /bin/bash -ic 'python -c "import lsst"'
        
    - name: upload
      if: github.ref == 'refs/heads/main'
      run: |
        echo ${PAT} | docker login -u beckermr --password-stdin 
        docker push stackvana:latest
      env:
        PAT: ${{ secrets.DOCKER_PAT }}
